// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3XO5ltdJ19rjZIFOrwO-kZNTP5oYmyWU',
    appId: '1:136210692187:web:71dd72dff016f4d0eea77e',
    messagingSenderId: '136210692187',
    projectId: 'shiny-booking',
    authDomain: 'shiny-booking.firebaseapp.com',
    storageBucket: 'shiny-booking.appspot.com',
    measurementId: 'G-9VJ29RWWLC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSXyMl5-un1giwgpsdwHeq3dR5cyjFxdw',
    appId: '1:136210692187:android:072635a7af4fa9b8eea77e',
    messagingSenderId: '136210692187',
    projectId: 'shiny-booking',
    storageBucket: 'shiny-booking.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByApqCgAIaSUpj_-btpVa3khuloHCWblY',
    appId: '1:136210692187:ios:bc4affb18a3072aceea77e',
    messagingSenderId: '136210692187',
    projectId: 'shiny-booking',
    storageBucket: 'shiny-booking.appspot.com',
    iosClientId: '136210692187-kq4gmefkubeb17hiordf14uofn0aqjhc.apps.googleusercontent.com',
    iosBundleId: 'com.example.shinyBooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByApqCgAIaSUpj_-btpVa3khuloHCWblY',
    appId: '1:136210692187:ios:bc4affb18a3072aceea77e',
    messagingSenderId: '136210692187',
    projectId: 'shiny-booking',
    storageBucket: 'shiny-booking.appspot.com',
    iosClientId: '136210692187-kq4gmefkubeb17hiordf14uofn0aqjhc.apps.googleusercontent.com',
    iosBundleId: 'com.example.shinyBooking',
  );
}
